import type { SessionSnapshot, SessionCall, GenerateOptions } from "../types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function groupByFunction(calls: SessionCall[]): Map<string, SessionCall[]> {
  const groups = new Map<string, SessionCall[]>();
  for (const call of calls) {
    let arr = groups.get(call.function);
    if (arr === undefined) {
      arr = [];
      groups.set(call.function, arr);
    }
    arr.push(call);
  }
  return groups;
}

function toCamelCase(name: string): string {
  // e.g. "create_order" → "createOrder", "create-order" → "createOrder"
  return name.replace(/[_-](\w)/g, (_, c: string) => c.toUpperCase());
}

function toMockName(fnName: string, prefix = "mock"): string {
  const camel = toCamelCase(fnName);
  return `${prefix}${camel[0]?.toUpperCase() ?? ""}${camel.slice(1)}`;
}

function toPythonFnName(fnName: string): string {
  // e.g. "createOrder" → "create_order", already snake_case stays
  return fnName
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "");
}

// ---------------------------------------------------------------------------
// Jest / Vitest generator
// ---------------------------------------------------------------------------

function generateJsVitest(session: SessionSnapshot, opts: GenerateOptions): string {
  const { target, includeTimings = false, oneCallPerFunction = false } = opts;
  const mockFn = target === "jest" ? "jest.fn()" : "vi.fn()";
  const resolvedValue = target === "jest" ? "mockResolvedValue" : "mockResolvedValue";

  const groups = groupByFunction(session.calls);
  const lines: string[] = [
    `// __mocks__ — auto-generated by ghost-doc mock generate`,
    `// Session: ${session.session}  Generated: ${new Date().toISOString()}`,
    `// Do not edit — regenerate with: ghost-doc mock generate`,
    "",
  ];

  if (target === "vitest") {
    lines.push('import { vi } from "vitest";', "");
  }

  for (const [fnName, calls] of groups) {
    const relevant = oneCallPerFunction ? [calls[0]!] : calls;
    const mockName = toMockName(fnName);

    if (relevant.length === 1) {
      const call = relevant[0]!;
      const retVal = JSON.stringify(call.return, null, 2).split("\n").join("\n  ");

      if (call.error !== null) {
        const errVal = JSON.stringify(call.error);
        lines.push(`export const ${mockName} = ${mockFn}.mockRejectedValue(${errVal});`);
      } else if (includeTimings && call.durationMs > 0) {
        lines.push(
          `export const ${mockName} = ${mockFn}.mockImplementation(`,
          `  () => new Promise((resolve) => setTimeout(() => resolve(${retVal}), ${call.durationMs})),`,
          `);`,
        );
      } else {
        lines.push(`export const ${mockName} = ${mockFn}.${resolvedValue}(${retVal});`);
      }
    } else {
      // Multiple responses: use mockResolvedValueOnce chain
      const parts: string[] = [`export const ${mockName} = ${mockFn}`];
      for (const call of relevant) {
        if (call.error !== null) {
          parts.push(`  .mockRejectedValueOnce(${JSON.stringify(call.error)})`);
        } else {
          const retVal = JSON.stringify(call.return);
          parts.push(`  .mockResolvedValueOnce(${retVal})`);
        }
      }
      lines.push(parts.join("\n") + ";");
    }

    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// pytest generator
// ---------------------------------------------------------------------------

function generatePytest(session: SessionSnapshot, opts: GenerateOptions): string {
  const { oneCallPerFunction = false } = opts;
  const groups = groupByFunction(session.calls);

  const lines: string[] = [
    "# __mocks__ — auto-generated by ghost-doc mock generate",
    `# Session: ${session.session}  Generated: ${new Date().toISOString()}`,
    "# Do not edit — regenerate with: ghost-doc mock generate",
    "",
  ];

  for (const [fnName, calls] of groups) {
    const pyName = `mock_${toPythonFnName(fnName)}`;
    const relevant = oneCallPerFunction ? [calls[0]!] : calls;

    if (relevant.length === 1) {
      const call = relevant[0]!;
      if (call.error !== null) {
        const errJson = JSON.stringify(call.error);
        lines.push(`def ${pyName}(*args, **kwargs):`, `    raise Exception(${errJson})`, "");
      } else {
        const retJson = JSON.stringify(call.return, null, 4);
        const indented = retJson.split("\n").join("\n    ");
        lines.push(`def ${pyName}(*args, **kwargs):`, `    return ${indented}`, "");
      }
    } else {
      // Multiple responses: use a call counter
      lines.push(`_${pyName}_calls = 0`, `_${pyName}_responses = [`);
      for (const call of relevant) {
        if (call.error !== null) {
          lines.push(`    {"__error__": ${JSON.stringify(call.error)}},`);
        } else {
          lines.push(`    ${JSON.stringify(call.return)},`);
        }
      }
      lines.push("]", "");
      lines.push(
        `def ${pyName}(*args, **kwargs):`,
        `    global _${pyName}_calls`,
        `    resp = _${pyName}_responses[_${pyName}_calls % len(_${pyName}_responses)]`,
        `    _${pyName}_calls += 1`,
        `    if isinstance(resp, dict) and "__error__" in resp:`,
        `        raise Exception(resp["__error__"])`,
        `    return resp`,
        "",
      );
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate a static mock file (Jest, Vitest, or pytest) from a recorded session.
 *
 * @param session  The recorded session snapshot.
 * @param opts     Target framework and generation options.
 * @returns        The generated file contents as a string.
 */
export function generateMocks(session: SessionSnapshot, opts: GenerateOptions): string {
  switch (opts.target) {
    case "jest":
    case "vitest":
      return generateJsVitest(session, opts);
    case "pytest":
      return generatePytest(session, opts);
    default:
      throw new Error(`Unknown mock target: ${String((opts as GenerateOptions).target)}`);
  }
}
