import { useEffect, useState, useCallback, useRef } from "react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface JSONSchema {
  type?: string | string[];
  properties?: Record<string, JSONSchema>;
  required?: string[];
  items?: JSONSchema;
  enum?: unknown[];
  format?: string;
  oneOf?: JSONSchema[];
}

interface ContractDefinition {
  version: "1.0";
  functionName: string;
  generatedAt: string;
  sampleCount: number;
  args: JSONSchema[];
  returns: JSONSchema;
  errors?: JSONSchema[];
}

interface ContractViolationDetail {
  path: string;
  expected: string;
  received: string;
  rule: string;
}

interface ContractViolation {
  functionName: string;
  spanId: string;
  traceId: string;
  timestamp: number;
  violations: ContractViolationDetail[];
}

interface SavedContract {
  name: string;
  file: string;
}

interface SchemaChange {
  path: string;
  kind: string;
  before: unknown;
  after: unknown;
}

interface DriftResult {
  functionName: string;
  isBreaking: boolean;
  changes: SchemaChange[];
  saved: ContractDefinition;
  current: ContractDefinition;
}

// ---------------------------------------------------------------------------
// localStorage helpers
// ---------------------------------------------------------------------------

function getPinned(): Set<string> {
  try {
    return new Set(JSON.parse(localStorage.getItem("gd:pinned") ?? "[]") as string[]);
  } catch {
    return new Set();
  }
}

function setPinned(set: Set<string>): void {
  localStorage.setItem("gd:pinned", JSON.stringify([...set]));
}

function getAnnotation(fnName: string): string {
  return localStorage.getItem(`gd:annotation:${fnName}`) ?? "";
}

function setAnnotation(fnName: string, text: string): void {
  if (text.trim() === "") {
    localStorage.removeItem(`gd:annotation:${fnName}`);
  } else {
    localStorage.setItem(`gd:annotation:${fnName}`, text);
  }
}

// ---------------------------------------------------------------------------
// Confidence score (0–100)
// ---------------------------------------------------------------------------

function computeConfidence(contract: ContractDefinition): number {
  const sampleScore = Math.min(contract.sampleCount / 50, 1) * 50;

  function countOneOf(schema: JSONSchema): number {
    let n = schema.oneOf ? 1 : 0;
    if (schema.properties) for (const v of Object.values(schema.properties)) n += countOneOf(v);
    if (schema.items) n += countOneOf(schema.items);
    return n;
  }
  const allSchemas = [...contract.args, contract.returns];
  const oneOfCount = allSchemas.reduce((s, sc) => s + countOneOf(sc), 0);
  const typeScore = Math.max(0, 30 - oneOfCount * 5);

  function hasFormat(schema: JSONSchema): boolean {
    if (schema.format) return true;
    if (schema.properties) return Object.values(schema.properties).some(hasFormat);
    return false;
  }
  const formatBonus = allSchemas.some(hasFormat) ? 20 : 0;

  return Math.round(Math.min(100, sampleScore + typeScore + formatBonus));
}

function confidenceColor(score: number): string {
  if (score >= 80) return "text-green-400";
  if (score >= 50) return "text-yellow-400";
  return "text-orange-400";
}

// ---------------------------------------------------------------------------
// TypeScript interface generator
// ---------------------------------------------------------------------------

function schemaToTs(schema: JSONSchema, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (schema.enum !== undefined) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (schema.oneOf !== undefined) return schema.oneOf.map((s) => schemaToTs(s, indent)).join(" | ");
  const t = Array.isArray(schema.type) ? schema.type[0] : schema.type;
  switch (t) {
    case "string":
      return schema.format ? `string /* ${schema.format} */` : "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `${schema.items ? schemaToTs(schema.items, indent) : "unknown"}[]`;
    case "object": {
      if (!schema.properties) return "Record<string, unknown>";
      const lines = ["{"];
      for (const [key, val] of Object.entries(schema.properties)) {
        const req = schema.required?.includes(key) ? "" : "?";
        lines.push(`${pad}  ${key}${req}: ${schemaToTs(val, indent + 1)};`);
      }
      lines.push(`${pad}}`);
      return lines.join("\n");
    }
    default:
      return "unknown";
  }
}

function contractToTs(contract: ContractDefinition): string {
  const lines = [
    `// auto-generated by Ghost Doc — ${contract.functionName}`,
    `// sampleCount: ${contract.sampleCount}  generatedAt: ${contract.generatedAt}`,
    "",
  ];
  contract.args.forEach((schema, i) => {
    lines.push(`export type ${contract.functionName}Arg${i} = ${schemaToTs(schema)};`);
  });
  if (contract.args.length > 0) lines.push("");
  lines.push(`export type ${contract.functionName}Return = ${schemaToTs(contract.returns)};`);
  if (contract.errors?.length) {
    lines.push("");
    contract.errors.forEach((schema, i) => {
      lines.push(`export type ${contract.functionName}Error${i} = ${schemaToTs(schema)};`);
    });
  }
  lines.push("");
  const argTypes = contract.args.map((_, i) => `${contract.functionName}Arg${i}`).join(", ");
  lines.push(
    `export type ${contract.functionName}Fn = (${argTypes ? `...args: [${argTypes}]` : ""}) => Promise<${contract.functionName}Return>;`,
  );
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main tab
// ---------------------------------------------------------------------------

type PanelView = "live" | "saved";
type DetailSection = "schema" | "typescript" | "violations" | "drift" | "annotations";

export function ContractsTab(): JSX.Element {
  const [panelView, setPanelView] = useState<PanelView>("live");
  const [contracts, setContracts] = useState<ContractDefinition[]>([]);
  const [savedContracts, setSavedContracts] = useState<SavedContract[]>([]);
  const [selected, setSelected] = useState<ContractDefinition | null>(null);
  const [violations, setViolations] = useState<ContractViolation[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState<string | null>(null);
  const [saving, setSaving] = useState<string | null>(null);
  const [minSamples, setMinSamples] = useState(1);
  const [coverageThreshold, setCoverageThreshold] = useState(10);
  const [pinned, setPinnedState] = useState<Set<string>>(getPinned);
  const [activeSection, setActiveSection] = useState<DetailSection>("schema");

  const fetchContracts = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/contracts?min_samples=${minSamples}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setContracts((await res.json()) as ContractDefinition[]);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }, [minSamples]);

  const fetchSaved = useCallback(async () => {
    try {
      const res = await fetch("/contracts/saved");
      if (!res.ok) return;
      setSavedContracts((await res.json()) as SavedContract[]);
    } catch {
      /* ignore */
    }
  }, []);

  useEffect(() => {
    void fetchContracts();
    void fetchSaved();
  }, [fetchContracts, fetchSaved]);

  const handleGenerateContract = useCallback(
    async (fnName: string) => {
      setGenerating(fnName);
      try {
        const res = await fetch(
          `/contracts/${encodeURIComponent(fnName)}?min_samples=${minSamples}`,
        );
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const contract = (await res.json()) as ContractDefinition;
        setContracts((prev) =>
          [...prev.filter((c) => c.functionName !== fnName), contract].sort((a, b) =>
            a.functionName.localeCompare(b.functionName),
          ),
        );
        setSelected(contract);
      } catch (err) {
        setError((err as Error).message);
      } finally {
        setGenerating(null);
      }
    },
    [minSamples],
  );

  const handleValidate = useCallback(async (contract: ContractDefinition) => {
    try {
      const res = await fetch("/contracts/validate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contract }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = (await res.json()) as { violations: ContractViolation[]; count: number };
      setViolations(data.violations);
      setActiveSection("violations");
    } catch (err) {
      setError((err as Error).message);
    }
  }, []);

  const handleSave = useCallback(
    async (contract: ContractDefinition) => {
      setSaving(contract.functionName);
      try {
        const res = await fetch("/contracts/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contract }),
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        await fetchSaved();
      } catch (err) {
        setError((err as Error).message);
      } finally {
        setSaving(null);
      }
    },
    [fetchSaved],
  );

  const handleLoadSaved = useCallback(async (name: string) => {
    try {
      const res = await fetch(`/contracts/saved/${encodeURIComponent(name)}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setSelected((await res.json()) as ContractDefinition);
      setViolations([]);
      setActiveSection("schema");
    } catch (err) {
      setError((err as Error).message);
    }
  }, []);

  const togglePin = useCallback((fnName: string) => {
    setPinnedState((prev) => {
      const next = new Set(prev);
      if (next.has(fnName)) next.delete(fnName);
      else next.add(fnName);
      setPinned(next);
      return next;
    });
  }, []);

  return (
    <div className="flex h-full overflow-hidden text-sm">
      {/* Left sidebar */}
      <div className="w-72 flex-shrink-0 border-r border-border flex flex-col overflow-hidden">
        {/* Controls */}
        <div className="px-3 py-2 border-b border-border flex-shrink-0 space-y-2">
          <div>
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-gray-500">Min samples</span>
              <span className="text-xs font-mono text-accent">{minSamples}</span>
            </div>
            <input
              type="range"
              min={1}
              max={50}
              value={minSamples}
              onChange={(e) => setMinSamples(Number(e.target.value))}
              onMouseUp={() => void fetchContracts()}
              onKeyUp={() => void fetchContracts()}
              className="w-full accent-accent"
            />
          </div>
          <div>
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-gray-500">Coverage gate</span>
              <span className="text-xs font-mono text-yellow-400">{coverageThreshold}</span>
            </div>
            <input
              type="range"
              min={1}
              max={100}
              value={coverageThreshold}
              onChange={(e) => setCoverageThreshold(Number(e.target.value))}
              className="w-full accent-yellow-400"
            />
          </div>
        </div>

        {/* View toggle */}
        <div className="flex border-b border-border flex-shrink-0">
          <PanelTab
            active={panelView === "live"}
            onClick={() => {
              setPanelView("live");
              void fetchContracts();
            }}
          >
            Live ({contracts.length})
          </PanelTab>
          <PanelTab
            active={panelView === "saved"}
            onClick={() => {
              setPanelView("saved");
              void fetchSaved();
            }}
          >
            Saved ({savedContracts.length})
          </PanelTab>
        </div>

        <div className="flex-1 overflow-y-auto">
          {loading && <div className="px-3 py-4 text-gray-600 text-xs">Loading…</div>}
          {error !== null && <div className="px-3 py-2 text-red-400 text-xs">{error}</div>}

          {panelView === "live" && !loading && contracts.length === 0 && (
            <div className="px-3 py-4 text-gray-600 text-xs">
              No contracts yet. Need ≥ {minSamples} call{minSamples !== 1 ? "s" : ""} per function.
            </div>
          )}

          {panelView === "live" &&
            contracts
              .slice()
              .sort((a, b) => a.functionName.localeCompare(b.functionName))
              .map((c) => {
                const conf = computeConfidence(c);
                const belowGate = c.sampleCount < coverageThreshold;
                const isPinned = pinned.has(c.functionName);
                return (
                  <button
                    key={c.functionName}
                    onClick={() => {
                      setSelected(c);
                      setViolations([]);
                      setActiveSection("schema");
                    }}
                    className={`w-full text-left px-3 py-2 border-b border-border/50 transition-colors ${
                      selected?.functionName === c.functionName
                        ? "bg-accent/20 text-accent"
                        : "text-gray-300 hover:bg-canvas/50"
                    } ${belowGate ? "border-l-2 border-l-yellow-600" : ""}`}
                  >
                    <div className="flex items-center justify-between gap-1">
                      <span className="font-mono truncate text-xs">{c.functionName}</span>
                      <div className="flex items-center gap-1 flex-shrink-0">
                        {isPinned && <span title="Pinned">📌</span>}
                        {belowGate && (
                          <span
                            className="text-yellow-400 text-xs"
                            title={`Only ${c.sampleCount} samples (gate: ${coverageThreshold})`}
                          >
                            ⚠
                          </span>
                        )}
                        <span className={`text-xs font-mono ${confidenceColor(conf)}`}>
                          {conf}%
                        </span>
                      </div>
                    </div>
                    <div className="text-xs text-gray-600 mt-0.5">
                      {c.sampleCount} samples · {c.args.length} arg{c.args.length !== 1 ? "s" : ""}
                      {c.errors?.length ? (
                        <span className="ml-1 text-orange-400">· errors</span>
                      ) : null}
                    </div>
                  </button>
                );
              })}

          {panelView === "saved" && savedContracts.length === 0 && (
            <div className="px-3 py-4 text-gray-600 text-xs">No saved contracts.</div>
          )}
          {panelView === "saved" &&
            savedContracts.map((s) => (
              <button
                key={s.name}
                onClick={() => void handleLoadSaved(s.name)}
                className="w-full text-left px-3 py-2 border-b border-border/50 text-gray-300 hover:bg-canvas/50 transition-colors"
              >
                <div className="font-mono text-xs truncate">{s.name}</div>
              </button>
            ))}
        </div>
      </div>

      {/* Right: detail panel */}
      {selected === null ? (
        <div className="flex-1 flex items-center justify-center text-gray-600 text-sm">
          Select a function to view its contract
        </div>
      ) : (
        <ContractDetail
          contract={selected}
          violations={violations}
          generating={generating}
          saving={saving}
          isPinned={pinned.has(selected.functionName)}
          activeSection={activeSection}
          onSectionChange={setActiveSection}
          onGenerate={() => void handleGenerateContract(selected.functionName)}
          onValidate={() => void handleValidate(selected)}
          onSave={() => void handleSave(selected)}
          onTogglePin={() => togglePin(selected.functionName)}
          onClearViolations={() => setViolations([])}
        />
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Contract detail panel
// ---------------------------------------------------------------------------

function ContractDetail({
  contract,
  violations,
  generating,
  saving,
  isPinned,
  activeSection,
  onSectionChange,
  onGenerate,
  onValidate,
  onSave,
  onTogglePin,
  onClearViolations,
}: {
  contract: ContractDefinition;
  violations: ContractViolation[];
  generating: string | null;
  saving: string | null;
  isPinned: boolean;
  activeSection: DetailSection;
  onSectionChange: (s: DetailSection) => void;
  onGenerate: () => void;
  onValidate: () => void;
  onSave: () => void;
  onTogglePin: () => void;
  onClearViolations: () => void;
}): JSX.Element {
  const conf = computeConfidence(contract);

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* Header */}
      <div className="px-4 py-3 border-b border-border flex items-center gap-2 flex-shrink-0 flex-wrap">
        <span className="font-mono font-semibold text-accent">{contract.functionName}</span>
        {isPinned && (
          <span className="text-xs text-yellow-400" title="Pinned — Re-infer won't overwrite">
            📌 pinned
          </span>
        )}
        <span className="text-xs text-gray-600">
          {contract.sampleCount} samples · {new Date(contract.generatedAt).toLocaleString()}
        </span>
        <span
          className={`text-xs font-mono font-semibold ${confidenceColor(conf)}`}
          title="Confidence score"
        >
          {conf}% confidence
        </span>
        <div className="flex-1" />
        <button
          onClick={onTogglePin}
          className={`text-xs px-2 py-1 rounded border transition-colors ${isPinned ? "border-yellow-700 text-yellow-400 bg-yellow-900/20" : "border-border text-gray-500 hover:border-yellow-700 hover:text-yellow-400"}`}
          title={isPinned ? "Unpin contract" : "Pin contract (protects from re-inference)"}
        >
          {isPinned ? "Unpin" : "Pin"}
        </button>
        <button
          onClick={isPinned ? undefined : onGenerate}
          disabled={generating === contract.functionName || isPinned}
          className="text-xs px-2 py-1 rounded bg-accent/20 text-accent hover:bg-accent/30 transition-colors disabled:opacity-50"
          title={isPinned ? "Unpin to re-infer" : "Re-infer contract from current spans"}
        >
          {generating === contract.functionName ? "Inferring…" : "↻ Re-infer"}
        </button>
        <button
          onClick={onValidate}
          className="text-xs px-2 py-1 rounded bg-border text-gray-400 hover:bg-accent/20 hover:text-accent transition-colors"
        >
          Validate spans
        </button>
        <button
          onClick={onSave}
          disabled={saving === contract.functionName}
          className="text-xs px-2 py-1 rounded bg-border text-gray-400 hover:bg-green-900/40 hover:text-green-400 transition-colors disabled:opacity-50"
          title="Save contract to disk"
        >
          {saving === contract.functionName ? "Saving…" : "↓ Save"}
        </button>
      </div>

      {/* Section tabs */}
      <div className="flex border-b border-border flex-shrink-0 overflow-x-auto">
        {(["schema", "typescript", "violations", "drift", "annotations"] as DetailSection[]).map(
          (sec) => (
            <SectionTab
              key={sec}
              active={activeSection === sec}
              onClick={() => onSectionChange(sec)}
            >
              {sec === "violations" ? (
                <>
                  Violations
                  {violations.length > 0 && (
                    <span className="ml-1.5 bg-red-700 text-white text-xs rounded-full px-1.5">
                      {violations.length}
                    </span>
                  )}
                </>
              ) : (
                sec.charAt(0).toUpperCase() + sec.slice(1)
              )}
            </SectionTab>
          ),
        )}
      </div>

      <div className="flex-1 overflow-y-auto p-4">
        {activeSection === "schema" && <SchemaView contract={contract} />}
        {activeSection === "typescript" && <TypeScriptView contract={contract} />}
        {activeSection === "violations" && (
          <ViolationsFeed violations={violations} onClear={onClearViolations} />
        )}
        {activeSection === "drift" && <DriftView contract={contract} />}
        {activeSection === "annotations" && <AnnotationsView fnName={contract.functionName} />}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Schema view
// ---------------------------------------------------------------------------

function SchemaView({ contract }: { contract: ContractDefinition }): JSX.Element {
  return (
    <div className="space-y-4">
      {contract.args.length > 0 && (
        <section>
          <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
            Arguments
          </h3>
          {contract.args.map((schema, i) => (
            <div key={i} className="mb-2">
              <div className="text-xs text-gray-500 mb-1">arg[{i}]</div>
              <CopyableBlock content={JSON.stringify(schema, null, 2)} />
            </div>
          ))}
        </section>
      )}
      <section>
        <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
          Return Value
        </h3>
        <CopyableBlock content={JSON.stringify(contract.returns, null, 2)} />
      </section>
      {contract.errors?.length ? (
        <section>
          <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
            Error Shapes
          </h3>
          {contract.errors.map((schema, i) => (
            <CopyableBlock key={i} content={JSON.stringify(schema, null, 2)} />
          ))}
        </section>
      ) : null}
    </div>
  );
}

// ---------------------------------------------------------------------------
// TypeScript view
// ---------------------------------------------------------------------------

function TypeScriptView({ contract }: { contract: ContractDefinition }): JSX.Element {
  const code = contractToTs(contract);
  return (
    <div>
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs text-gray-500">TypeScript interfaces inferred from contract</span>
        <button
          onClick={() => {
            const blob = new Blob([code], { type: "text/plain" });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `${contract.functionName}.d.ts`;
            a.click();
            URL.revokeObjectURL(url);
          }}
          className="text-xs px-2 py-1 rounded bg-border text-gray-400 hover:bg-accent/20 hover:text-accent transition-colors"
        >
          ↓ Download .d.ts
        </button>
      </div>
      <CopyableBlock content={code} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Drift view
// ---------------------------------------------------------------------------

function DriftView({ contract }: { contract: ContractDefinition }): JSX.Element {
  const [drift, setDrift] = useState<DriftResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchDrift = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(
        `/contracts/${encodeURIComponent(contract.functionName)}/drift?min_samples=1`,
      );
      if (res.status === 404) {
        setError("No saved contract found. Save the contract first.");
        return;
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      setDrift((await res.json()) as DriftResult);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }, [contract.functionName]);

  useEffect(() => {
    void fetchDrift();
  }, [fetchDrift]);

  if (loading) return <div className="text-gray-600 text-xs">Comparing…</div>;
  if (error)
    return (
      <div className="space-y-2">
        <div className="text-gray-500 text-xs">{error}</div>
        <button
          onClick={() => void fetchDrift()}
          className="text-xs px-2 py-1 rounded bg-border text-gray-400 hover:text-accent transition-colors"
        >
          Retry
        </button>
      </div>
    );
  if (!drift) return <div className="text-gray-600 text-xs">No drift data.</div>;

  return (
    <div className="space-y-4">
      <div
        className={`flex items-center gap-2 px-3 py-2 rounded border text-xs font-semibold ${
          drift.isBreaking
            ? "bg-red-950/40 border-red-800 text-red-400"
            : "bg-green-950/40 border-green-800 text-green-400"
        }`}
      >
        {drift.isBreaking ? "⚠ Breaking changes detected" : "✓ No breaking changes"}
        <span className="font-normal opacity-70">saved → current</span>
        <button
          onClick={() => void fetchDrift()}
          className="ml-auto text-xs opacity-60 hover:opacity-100"
        >
          ↻
        </button>
      </div>

      {drift.changes.length === 0 ? (
        <div className="text-gray-500 text-xs">Schemas are identical.</div>
      ) : (
        <div className="space-y-2">
          {drift.changes.map((ch, i) => {
            const isBreakingChange = [
              "type_changed",
              "required_added",
              "field_removed",
              "enum_changed",
            ].includes(ch.kind);
            return (
              <div
                key={i}
                className={`px-3 py-2 rounded border text-xs ${isBreakingChange ? "border-red-900/50 bg-red-950/20" : "border-border bg-canvas"}`}
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-yellow-400">{ch.path}</span>
                  <span
                    className={`px-1.5 py-0.5 rounded text-xs ${isBreakingChange ? "bg-red-900/50 text-red-400" : "bg-border text-gray-400"}`}
                  >
                    {ch.kind}
                  </span>
                </div>
                <div className="flex gap-4 text-xs">
                  <span className="text-gray-500">
                    before:{" "}
                    <span className="font-mono text-red-300">{JSON.stringify(ch.before)}</span>
                  </span>
                  <span className="text-gray-500">
                    after:{" "}
                    <span className="font-mono text-green-300">{JSON.stringify(ch.after)}</span>
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Annotations view
// ---------------------------------------------------------------------------

function AnnotationsView({ fnName }: { fnName: string }): JSX.Element {
  const [text, setText] = useState(() => getAnnotation(fnName));

  useEffect(() => {
    setText(getAnnotation(fnName));
  }, [fnName]);

  return (
    <div className="space-y-2">
      <div className="text-xs text-gray-500">
        Notes about <span className="font-mono text-accent">{fnName}</span> — stored locally in your
        browser.
      </div>
      <textarea
        value={text}
        onChange={(e) => {
          setText(e.target.value);
          setAnnotation(fnName, e.target.value);
        }}
        placeholder="Add notes about this function's behavior, known edge cases, quirks…"
        className="w-full h-48 text-xs bg-canvas border border-border rounded p-3 text-gray-300 placeholder-gray-600 focus:outline-none focus:border-accent resize-y font-mono"
      />
      <div className="text-xs text-gray-700">Saved automatically as you type.</div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Violations feed
// ---------------------------------------------------------------------------

function ViolationsFeed({
  violations,
  onClear,
}: {
  violations: ContractViolation[];
  onClear: () => void;
}): JSX.Element {
  if (violations.length === 0) {
    return (
      <div className="text-gray-600 text-xs">
        No violations. Click "Validate spans" to check recent calls against this contract.
      </div>
    );
  }
  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <span className="text-xs text-gray-500">{violations.length} violation(s)</span>
        <button
          onClick={onClear}
          className="text-xs text-gray-600 hover:text-gray-400 transition-colors"
        >
          Clear
        </button>
      </div>
      <div className="space-y-3">
        {violations.map((v, i) => (
          <div key={i} className="bg-canvas border border-red-900/50 rounded p-3 text-xs">
            <div className="font-mono text-gray-400 mb-2">
              span <span className="text-gray-600">{v.spanId.slice(0, 8)}…</span>
            </div>
            {v.violations.map((d, j) => (
              <div key={j} className="flex gap-2 text-xs mb-1">
                <span className="font-mono text-yellow-400">{d.path}</span>
                <span className="text-gray-600">[{d.rule}]</span>
                <span className="text-gray-500">expected</span>
                <span className="text-green-400">{d.expected}</span>
                <span className="text-gray-500">got</span>
                <span className="text-red-400">{d.received}</span>
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Copyable code block
// ---------------------------------------------------------------------------

function CopyableBlock({ content }: { content: string }): JSX.Element {
  const [copied, setCopied] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const handleCopy = useCallback(() => {
    void navigator.clipboard.writeText(content).then(() => {
      setCopied(true);
      if (timer.current !== null) clearTimeout(timer.current);
      timer.current = setTimeout(() => setCopied(false), 1500);
    });
  }, [content]);
  return (
    <div className="relative group">
      <pre className="text-xs font-mono bg-canvas border border-border rounded p-3 overflow-x-auto text-gray-300 whitespace-pre-wrap">
        {content}
      </pre>
      <button
        onClick={handleCopy}
        className="absolute top-2 right-2 text-xs px-1.5 py-0.5 rounded bg-border/80 text-gray-500 hover:text-accent hover:bg-accent/20 transition-colors opacity-0 group-hover:opacity-100"
        title="Copy to clipboard"
      >
        {copied ? "✓" : "copy"}
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function PanelTab({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}): JSX.Element {
  return (
    <button
      onClick={onClick}
      className={`flex-1 px-3 py-2 text-xs font-medium transition-colors border-b-2 ${active ? "border-accent text-accent" : "border-transparent text-gray-500 hover:text-gray-300"}`}
    >
      {children}
    </button>
  );
}

function SectionTab({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}): JSX.Element {
  return (
    <button
      onClick={onClick}
      className={`px-4 py-2 text-xs font-medium transition-colors border-b-2 whitespace-nowrap ${active ? "border-accent text-accent" : "border-transparent text-gray-500 hover:text-gray-300"}`}
    >
      {children}
    </button>
  );
}
